export const SET_GALLERY_FILTER = 'SET_GALLERY_FILTER'

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'

export const USER_LOGGED_IN = 'USER_LOGGED_IN'

export const IMAGE_PUBLIC_STATUS = 'IMAGE_PUBLIC_STATUS'

export const FUZZY_SEARCH = 'FUZZY_SEARCH'

export const SET_ACTIVE_IMAGE = 'SET_ACTIVE_IMAGE'
